apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-deployment
  name: test-deployment
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: golangtest
    spec:
      containers:
      - name: main
        image: kenkoii/golangtest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000