kind: Service
apiVersion: v1
metadata:
  name: test-service
spec:
  selector:
    # Selector to Identify pods to loadbalance
    app: golangtest
  type: LoadBalancer
  ports:
  - protocol: TCP
    # I have no Idea what this is for
    nodePort: 32131
    # Port that is accessible outside
    port: 3030
    # Port that are exposed inside pods/containers
    targetPort: 3000

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-deployment
  name: test-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: golangtest
    spec:
      containers:
      - name: main
        image: kenkoii/golangtest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000

# ---
# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   labels:
#     app: wikixmysql
#   name: wikixmysql
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: wikixmysql
#     spec:
#       containers:
#       - name: mysql
#         image: mysql:5.6
#         ports:
#         - containerPort: 3306
#         livenessProbe:
#           httpGet:
#             path: /
#             port: 3306
