apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: go-kube-deployment
  name: go-kube-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: go-kube
    spec:
      containers:
      - name: main
        image: gcr.io/wikix-staging/go-kube
        ports:
        - containerPort: 3000